import { createContext, ReactNode, useContext } from 'react'

export type Language = 'es' | 'en'

export type TranslationKey = keyof typeof translations.es

const translations = {
  es: {
    navHome: 'Inicio', navAccess: 'Acceso', navProducts: 'Productos', navContact: 'Contacto',
    ariaHome: 'Ir al inicio de A/S Nexus', ariaMenuOpen: 'Abrir menú principal', ariaMenuClose: 'Cerrar menú principal', ariaNav: 'Navegación principal', ariaPrefs: 'Preferencias de interfaz', ariaLang: 'Idioma', ariaTheme: 'Tema', ariaSpanish: 'Seleccionar idioma español', ariaEnglish: 'Seleccionar idioma inglés',
    themeDark: 'Oscuro', themeLight: 'Claro', ariaDark: 'Activar tema oscuro', ariaLight: 'Activar tema claro', rights: 'Todos los derechos reservados',
    heroTitle: 'La carne y el metal, entrelazados\nFortalece tus propias capacidades', heroQuote: '“Potenciamos lo humano con criterio y control”', heroDescription: 'Implantes calibrados y optimizados para tu ritmo, exigencia y la forma en que la ciudad obliga a superarte.',
    statProducts: 'Productos', statCart: 'Mejoras en carrito', statStatus: 'Estado', statSync: 'Sincronizando', statActive: 'Activo',
    accessTitle: 'Acceso', accessDescription: 'Se debe validar tu identidad para operar en la red. Solo las cuentas con correo verificado pueden ingresar.', recommendedFlow: 'Flujo recomendado', accessStep1: 'Registrate con tu correo operativo.', accessStep2: 'Se ha notificado a su bandeja de entrada.', accessStep3: 'Por favor, debe abrir el enlace seguro y verificar los datos.', activeSession: 'Sesión activa', status: 'Estado', emailVerified: 'correo validado', emailPending: 'pendiente de validación', signOut: 'Cerrar sesión', email: 'Correo', password: 'Clave', authNote: 'Luego del alta enviaremos un correo de Nodemailer con el enlace seguro gestionado por Firebase.', processing: 'Procesando...', signIn: 'Ingresar', signUp: 'Registrarse', network: 'Red', accountCreated: 'Cuenta creada', verifyEmailTitle: 'Verifica el correo electrónico registrado', verifyEmailCopy: 'Ya enviamos el correo seguro. El enlace recibido es para habilitar la cuenta y seguir el estado de compra desde nuestra red.', nextStep: 'Siguiente paso', openNetwork: 'Abrir red', understood: 'Entendido',
    productsTitle: 'Productos', productsSubtitle: 'Nuevas mejoras y pedidos personalizados a tu alcance.', cart: 'Carrito', item: 'item', items: 'items', openImage: 'Abrir imagen ampliada de', clickZoom: 'Click para ampliar', hideDetails: 'Ocultar detalles', viewDetails: 'Ver detalles', addToCart: 'Agregar al carrito', total: 'Total', category: 'Categoría', expandedView: 'Vista ampliada de', close: 'Cerrar', cartPreview: 'Vista previa', emptyCartHeader: 'No se han agregado productos al carrito.', emptyCart: 'Añade otras mejoras para ver el resumen del carrito y avanzar al checkout.', remove: 'Quitar', removeUnit: 'Quitar una unidad de', addUnit: 'Agregar una unidad de', subtotal: 'Subtotal', checkout: 'Ir al checkout', loginCheckout: 'Ingresar a la red para completar el checkout.',
    contactTitle: 'Contacto', contactDescription: '¿Buscando se parte de nuestra red? Necesitamos talentos para desarrollo de implantes, operaciones de campo y seguridad corporativa en los distritos de Night City.', contactNote: 'Tu solicitud es remitida por Nodemailer: notifica al equipo y te devuelve una respuesta automatizada a tu correo registrado.', nameAlias: 'Nombre o alias operativo', contactEmail: 'Correo de contacto', experience: 'Contanos tu especialidad y experiencia previa', sending: 'Enviando...', apply: 'Postular',
    verifyOkEyebrow: 'Identidad validada', verifyOkTitle: 'Correo verificado correctamente.', verifyOkDescription: 'La identidad se encuentra confirmada. Regresa a Acceso e iniciá sesión para operar dentro de A/S Nexus.', verifyPendingEyebrow: 'Identidad pendiente de verificar acceso', verifyPendingTitle: 'Falta abrir el enlace seguro del correo.', verifyPendingDescription: 'Revisa la bandeja de entrada, spam o promociones del correo usado al registrarte para completar el estado final.', verifySteps: 'Pasos para el chequeo', verifyStep1: 'Un correo emitido por Firebase Authentication.', verifyStep2: 'Un correo adicional de A/S Nexus con Nodemailer para guiar el proceso.', verifyStep3: 'Un enlace seguro que valida tu cuenta y te devuelve a esta interfaz.', verifyNoteTitle: 'A tener en cuenta:', verifyNote: 'Si ya validaste el correo, regresa a Acceso y tu login queda habilitado. Si no lo hiciste, vuelve a ingresar a tu casilla de mail registrado con el enlace pendiente.', goAccess: 'Ir a Acceso',
  },
  en: {
    navHome: 'Home', navAccess: 'Access', navProducts: 'Products', navContact: 'Contact',
    ariaHome: 'Go to A/S Nexus home', ariaMenuOpen: 'Open main menu', ariaMenuClose: 'Close main menu', ariaNav: 'Main navigation', ariaPrefs: 'Interface preferences', ariaLang: 'Language', ariaTheme: 'Theme', ariaSpanish: 'Select Spanish language', ariaEnglish: 'Select English language',
    themeDark: 'Dark', themeLight: 'Light', ariaDark: 'Enable dark theme', ariaLight: 'Enable light theme', rights: 'All rights reserved',
    heroTitle: 'Flesh and metal, intertwined\nStrengthen your own capabilities', heroQuote: '“We enhance humanity with judgment and control”', heroDescription: 'Calibrated implants optimized for your pace, demands, and the way the city forces you to evolve.',
    statProducts: 'Products', statCart: 'Cart upgrades', statStatus: 'Status', statSync: 'Syncing', statActive: 'Active',
    accessTitle: 'Access', accessDescription: 'Your identity must be validated to operate on the network. Only accounts with verified email can sign in.', recommendedFlow: 'Recommended flow', accessStep1: 'Register with your operational email.', accessStep2: 'A notification has been sent to your inbox.', accessStep3: 'Please open the secure link and verify your data.', activeSession: 'Active session', status: 'Status', emailVerified: 'email verified', emailPending: 'pending validation', signOut: 'Sign out', email: 'Email', password: 'Password', authNote: 'After registration, we will send a Nodemailer email with the secure link managed by Firebase.', processing: 'Processing...', signIn: 'Sign in', signUp: 'Register', network: 'Network', accountCreated: 'Account created', verifyEmailTitle: 'Verify the registered email address', verifyEmailCopy: 'We already sent the secure email. The received link enables the account and lets you follow purchase status from our network.', nextStep: 'Next step', openNetwork: 'Open network', understood: 'Understood',
    productsTitle: 'Products', productsSubtitle: 'New upgrades and custom requests within reach.', cart: 'Cart', item: 'item', items: 'items', openImage: 'Open enlarged image of', clickZoom: 'Click to enlarge', hideDetails: 'Hide details', viewDetails: 'View details', addToCart: 'Add to cart', total: 'Total', category: 'Category', expandedView: 'Expanded view of', close: 'Close', cartPreview: 'Preview', emptyCartHeader: 'No products have been added to the cart.', emptyCart: 'Add more upgrades to see the cart summary and proceed to checkout.', remove: 'Remove', removeUnit: 'Remove one unit of', addUnit: 'Add one unit of', subtotal: 'Subtotal', checkout: 'Go to checkout', loginCheckout: 'Sign in to the network to complete checkout.',
    contactTitle: 'Contact', contactDescription: 'Looking to join our network? We need talent for implant development, field operations, and corporate security in Night City districts.', contactNote: 'Your application is routed through Nodemailer: it notifies the team and returns an automated response to your registered email.', nameAlias: 'Name or operational alias', contactEmail: 'Contact email', experience: 'Tell us your specialty and previous experience', sending: 'Sending...', apply: 'Apply',
    verifyOkEyebrow: 'Identity validated', verifyOkTitle: 'Email verified successfully.', verifyOkDescription: 'Your identity is confirmed. Return to Access and sign in to operate inside A/S Nexus.', verifyPendingEyebrow: 'Identity pending access verification', verifyPendingTitle: 'Open the secure email link to continue.', verifyPendingDescription: 'Check the inbox, spam, or promotions folder for the email used during registration to complete the final status.', verifySteps: 'Verification steps', verifyStep1: 'An email sent by Firebase Authentication.', verifyStep2: 'An additional A/S Nexus email with Nodemailer to guide the process.', verifyStep3: 'A secure link that validates your account and returns you to this interface.', verifyNoteTitle: 'Keep in mind:', verifyNote: 'If you already verified the email, return to Access and your login will be enabled. If not, go back to the registered mailbox and open the pending link.', goAccess: 'Go to Access',
  },
} as const

const I18nContext = createContext<{ language: Language; t: (key: TranslationKey) => string } | null>(null)

export function translate(language: Language, key: TranslationKey) {
  return translations[language][key]
}

export function I18nProvider({ children, language }: { children: ReactNode; language: Language }) {
  return <I18nContext.Provider value={{ language, t: (key) => translate(language, key) }}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used within I18nProvider')
  return context
}
